# --- Constants ---
SCREEN_WIDTH, SCREEN_HEIGHT = 800, 600
FPS = 60
TIMELINE_HEIGHT = 120
FRAME_WIDTH = 10
TIMELINE_Y = SCREEN_HEIGHT - TIMELINE_HEIGHT  # timeline height
MAX_TIME = 5.0
SAVE_MODE = False
ASSETS_FOLDER = "assets"
SIDEBAR_WIDTH = 200